### ISSUE TITLE
[JS to Python] JSからファイルをpythonに渡す

### ISSUE THREAD

**Issue by ROBO358** [YHU-team18/Read-files-and-learn-words#10]
# 概要
読み込まれたPDFファイルはJavaScriptで取得するため、Python側で受け取りをさせる。

# 目的
PythonでPDFの処理を行いたいため

# 提案内容
JavaScriptでPDFを取得した想定で変数の中身をPythonに受け渡す処理をJavaScript・Pythonの両方で書く。

# タスク

- [x] ボタンを押すことで、変数に架空のPDFデータを持つJavaScriptを書く
- [x] JavaScriptからPythonへの変数の中身を転送する処理を書く
- [x] Pythonで受け取ったファイルが正常か、確認する。

**Comment by ROBO358** [comment]
セキュリティ的な問題(https://www.hos.co.jp/blog/20180129/ )で、D&Dしたファイルをバックエンド側に送信できなさそうなので、解決策が見つかるまでファイル選択のフォームを使用した方法にしたいです。
<img width="235" alt="image" src="https://user-images.githubusercontent.com/18186312/174422685-b98e3a08-f683-4ece-a1ea-b196ab54525a.png">

どうでしょう…

**Comment by makinzm** [comment]
JSでfileを読み込めますか?
 もし読み込めるなら,JS側でPythonを呼び出すのもありかなと思いましたがいかがでしょうか?

**Comment by ROBO358** [comment]
> JSでfileを読み込めますか? もし読み込めるなら,JS側でPythonを呼び出すのもありかなと思いましたがいかがでしょうか?

最初にその手法で実装をしようとして失敗したので、現在の手法にしていたのですが、
もう一度コーディングしていく中で解決したので、JSからAjaxによりPOST、Pythonでの受け取りという形になりました👍
これにより、D&Dが有効のままにになっています🎉
