### ISSUE TITLE
[ボタンを押してCreate] <.pyファイルからデータを追加>

### ISSUE THREAD

**Issue by makinzm** [YHU-team18/Read-files-and-learn-words#27]
# 概要

ボタンを追加することで,DBが追加されるようにする.
(例えば,ボタンを押すと [for_Dev.py](https://github.com/YHU-team18/Read-files-and-learn-words/blob/main/src/for_dev_CR.py) を実行する.)

# 目的

python処理をどのように実行させるか確認するため

# 提案内容

- [Djangoで機械学習アプリケーション ~Webアプリ作成~](https://qiita.com/T_gdmuy/items/f87bbcecb3edfca8f07d)
- [Djangoを用いてhtmlからPythonファイルを実行する](https://qiita.com/kkkei257/items/b3292b443699ecfb148f)
を参考にする

# タスク

- [ ] 細かいタスクに分解できているなら書き出す

**Comment by ROBO358** [comment]
現状、 #22 ではHTML/JS上でPOST処理を実行させ、Python側で受け取る形で実装されています。([Djangoを用いてhtmlからPythonファイルを実行する](https://qiita.com/kkkei257/items/b3292b443699ecfb148f)のような形)

DBの追加等の処理であれば、以下のように`Models`を使用したほうが処理的にも簡潔に制作できると思われます。
[【Django】フォームForm：データベースへの新規登録・更新機能を組み込む（instance変数） | OFFICE54](https://office54.net/python/django/form-database-instance)
[Django Modelsを使ってデータを登録する | Hornet|静岡拠点のWeb、ホームページ制作](https://hombre-nuevo.com/python/python0043/)

**Comment by makinzm** [comment]
@ROBO358 
今日明日で,Djangoも見ますが,厳しそうならひとまずでこちらの着手も考えてみるといった流れです🙇‍♂️
