### ISSUE TITLE
[BoW] <Wikiデータによる頻度のデータ & 発音記号>

### ISSUE THREAD

**Issue by makinzm** [YHU-team18/Read-files-and-learn-words#37]
# 概要

PDFを追加した際のimportanceの値を決定させる際に,
wikiデータと元pdfの出現頻度を考慮して決定したい.

そのため,BoWの処理に似通ってWikiのデータの算出,及び発音記号のデータのdictionaryの関数の作成をお願いしたいです🙇‍♂️

# 目的

PDFからデータを入れた際の,importanceや発音記号を適切に設定し,利便性を上げる.

# 提案内容

もし頻度データと発音記号が別のissueに分割した方が良さそうなら,それで確認お願いいたします🙇‍♂️

# タスク

- [ ] 細かいタスクに分解できているなら書き出す

**Comment by hisashi-y** [comment]
今あるget_BOW, get_meaningに類似した形で、関数の返り値として{'単語': (wikiでの頻度, '発音記号')}などを返す形でいいでしょうか？もしくは別々の関数にして{'単語': wikiでの頻度}, {'単語': 発音記号}で別個で返すこともできると思います。
後者の方がのちの工程で使いやすいかもしれないですね。

**Comment by makinzm** [comment]
別々で大丈夫です!

**Comment by hisashi-y** [comment]
ありがとうございます！了解です。
現在あるPDFtoBoW.pyに追記する形で実装してみます。

**Comment by makinzm** [comment]
はい!大丈夫です! ありがとうございます.
